#!/usr/bin/env python3
"""Recompute automated Android/iOS data-device evidence from current inputs."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

from check_interaction_device_evidence import (
    app_hashes,
    runtime_input_hashes,
    sha256,
    test_hashes,
)
from run_data_device_tests import png_dimensions
from data_test_cases import required_data_cases
from check_data_coverage import declared_blocks


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bindings", required=True)
    parser.add_argument("--runtime-manifest", required=True)
    parser.add_argument("--test-root", required=True)
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--evidence", required=True)
    args = parser.parse_args()

    evidence = json.loads(Path(args.evidence).read_text(encoding="utf-8"))
    if evidence.get("generator") not in {
        "run_data_device_tests.py",
        "run_client_device_tests.py",
    }:
        raise SystemExit(
            "ERROR: data device evidence must be generated by "
            "run_data_device_tests.py or run_client_device_tests.py"
        )
    if evidence.get("platform") not in {"android", "ios"}:
        raise SystemExit("ERROR: target client platform must be android or ios")
    bindings_path = Path(args.bindings).resolve()
    runtime_path = Path(args.runtime_manifest).resolve()
    test_root = Path(args.test_root).resolve()
    project_root = Path(args.project_root).resolve()
    failures = []
    platform = str(evidence.get("platform") or "")
    bindings = json.loads(bindings_path.read_text(encoding="utf-8"))
    runtime = json.loads(runtime_path.read_text(encoding="utf-8"))
    required_cases = [
        case
        for case in required_data_cases(bindings, runtime)
        if case.startswith(("DATA-SLOT:", "DATA-STATE:"))
    ]
    slot_bindings = {}
    for entry in bindings.get("bindings") or []:
        field = (entry.get("binding") or {}).get("field")
        if not isinstance(field, dict):
            continue
        state = entry.get("state")
        qualifier = f"{state}:" if state is not None else ""
        slot_bindings[f"DATA-SLOT:{qualifier}{entry.get('node')}"] = {
            "key": f"iff:{entry.get('node')}",
            "field": str(field.get("jsonPath") or ""),
        }
    state_targets = {
        f"DATA-STATE:{operation.get('id')}:{state}": (
            operation.get("stateTargets") or {}
        ).get(state)
        for operation in runtime.get("operations") or []
        for state in operation.get("requiredStates") or []
    }
    if evidence.get("requiredCases") != required_cases:
        failures.append("device required data cases differ")
    cases = evidence.get("cases") or {}
    for case_id in required_cases:
        result = cases.get(case_id) or {}
        if result.get("result") != "success" or result.get("skipped"):
            failures.append(f"missing successful device case: {case_id}")
        blocks = declared_blocks(test_root, case_id, "testWidgets")
        if not blocks:
            failures.append(f"{case_id}: device case missing testWidgets source")
        elif not any(re.search(r"\bapp\.main\s*\(", block) for block in blocks):
            failures.append(f"{case_id}: device case does not start app.main")
        else:
            if platform == "android" and not any(
                re.search(r"\.convertFlutterSurfaceToImage\s*\(", block)
                for block in blocks
            ):
                failures.append(
                    f"{case_id}: Android screenshot surface not converted"
                )
            expected_count = 2 if case_id.startswith("DATA-SLOT:") else 1
            for index in range(1, expected_count + 1):
                linked = False
                for block in blocks:
                    assignment = re.search(
                        r"\b([A-Za-z_]\w*)\s*=\s*await\s+"
                        r"[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*\.takeScreenshot\s*\(\s*['\"]"
                        + re.escape(f"{case_id}:{index}")
                        + r"['\"]",
                        block,
                    )
                    if not assignment:
                        continue
                    marker = re.compile(
                        re.escape(f"IFF_DATA_CAPTURE|{case_id}|{index}|")
                        + r"\$\{\s*base64Encode\s*\(\s*"
                        + re.escape(assignment.group(1))
                        + r"\s*\)\s*\}"
                    )
                    if marker.search(block):
                        linked = True
                        break
                if not linked:
                    failures.append(
                        f"{case_id}: missing automated screenshot source {index}"
                    )
        if case_id.startswith("DATA-SLOT:") and blocks:
            slot = slot_bindings[case_id]
            key_assertion = re.compile(
                r"find\.byKey\s*\(\s*(?:const\s+)?ValueKey(?:<[^>]+>)?\s*\(\s*['\"]"
                + re.escape(slot["key"])
                + r"['\"]"
            )
            if not any(key_assertion.search(block) for block in blocks):
                failures.append(f"{case_id}: missing exact slot target {slot['key']}")
            field_path = slot["field"]
            if not any(
                re.search(r"['\"]" + re.escape(field_path) + r"['\"]", block)
                for block in blocks
            ):
                failures.append(f"{case_id}: missing bound field {field_path}")
            visible_values = {
                value
                for block in blocks
                for value in re.findall(
                    r"\bexpect(?:Later)?\s*\(\s*find\.text\s*\(\s*['\"]([^'\"]+)['\"]",
                    block,
                )
            }
            if len(visible_values) < 2:
                failures.append(f"{case_id}: needs two distinct visible assertions")
            parts = [
                part
                for part in re.split(r"[.\[\]]+", field_path)
                if part and part != "$"
            ]
            field_name = parts[-1] if parts else ""
            input_values = {
                value.strip()
                for block in blocks
                for value in re.findall(
                    r"['\"]"
                    + re.escape(field_name)
                    + r"['\"]\s*:\s*([^,}\n]+)",
                    block,
                )
            }
            if len(input_values) < 2:
                failures.append(f"{case_id}: needs two distinct bound field inputs")
        if case_id.startswith("DATA-STATE:") and blocks:
            target = state_targets.get(case_id)
            if not (
                isinstance(target, dict)
                and isinstance(target.get("key"), str)
                and target.get("key")
                and isinstance(target.get("text"), str)
                and target.get("text")
            ):
                failures.append(f"{case_id}: missing structured state target key/text")
            else:
                key_assertion = re.compile(
                    r"find\.byKey\s*\(\s*(?:const\s+)?ValueKey(?:<[^>]+>)?\s*\(\s*['\"]"
                    + re.escape(target["key"])
                    + r"['\"]"
                )
                if not any(key_assertion.search(block) for block in blocks):
                    failures.append(
                        f"{case_id}: missing exact state target {target['key']}"
                    )
                text_assertion = re.compile(
                    r"\bexpect(?:Later)?\s*\(\s*find\.text\s*\(\s*['\"]"
                    + re.escape(target["text"])
                    + r"['\"]"
                )
                if not any(text_assertion.search(block) for block in blocks):
                    failures.append(
                        f"{case_id}: missing visible state text {target['text']}"
                    )
    command = evidence.get("command") or []
    device_id = str(evidence.get("deviceId") or "")
    if not (
        isinstance(command, list)
        and len(command) >= 6
        and Path(str(command[0])).name == "flutter"
        and command[1] == "test"
        and "--machine" in command
        and any(
            command[index : index + 2] in (["-d", device_id], ["--device-id", device_id])
            for index in range(max(0, len(command) - 1))
        )
        and device_id
        and evidence.get("deviceTargetPlatform") == platform
        and evidence.get("actualPlatforms") == [platform]
        and evidence.get("exitCode") == 0
    ):
        failures.append("command/device mismatch")
    if evidence.get("appHashes") != app_hashes(project_root):
        failures.append("stale device appHashes")
    if evidence.get("bindingsHash") != sha256(bindings_path):
        failures.append("stale device bindingsHash")
    if evidence.get("runtimeManifestHash") != sha256(runtime_path):
        failures.append("stale device runtimeManifestHash")
    if evidence.get("testHashes") != test_hashes(test_root):
        failures.append("stale device testHashes")
    if evidence.get("runtimeInputHashes") != runtime_input_hashes(project_root):
        failures.append("stale device runtimeInputHashes")
    current_captures = []
    for capture in evidence.get("captures") or []:
        path = Path(str(capture.get("path") or "")).resolve()
        if not path.is_file():
            failures.append(f"stale device capture: {capture.get('caseId')}: missing")
            continue
        payload = path.read_bytes()
        try:
            width, height = png_dimensions(payload)
        except SystemExit:
            failures.append(f"stale device capture: {capture.get('caseId')}: invalid PNG")
            continue
        current = {
            "caseId": capture.get("caseId"),
            "index": capture.get("index"),
            "path": str(path),
            "sha256": hashlib.sha256(payload).hexdigest(),
            "width": width,
            "height": height,
            "byteLength": len(payload),
        }
        current_captures.append(current)
        if current != capture:
            failures.append(f"stale device capture: {capture.get('caseId')}")
    for case_id in required_cases:
        records = [record for record in current_captures if record["caseId"] == case_id]
        expected_count = 2 if case_id.startswith("DATA-SLOT:") else 1
        if len(records) != expected_count:
            failures.append(f"{case_id}: requires {expected_count} current capture(s)")
        elif case_id.startswith("DATA-SLOT:") and len(
            {record["sha256"] for record in records}
        ) != 2:
            failures.append(f"{case_id}: current capture pixels did not change")
    if failures:
        raise SystemExit(
            "ERROR: data device evidence failed:\n"
            + "\n".join(f"- {failure}" for failure in failures)
        )
    print("ok data device evidence")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
