#!/usr/bin/env python3
"""Re-run and validate current live API evidence through real HTTP."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from run_live_api_tests import execute_operations, sha256


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api-contract", required=True)
    parser.add_argument("--runtime-manifest", required=True)
    parser.add_argument("--report", required=True)
    parser.add_argument("--timeout", type=float, default=10.0)
    args = parser.parse_args()

    contract_path = Path(args.api_contract).resolve()
    runtime_path = Path(args.runtime_manifest).resolve()
    report = json.loads(Path(args.report).read_text(encoding="utf-8"))
    if report.get("generator") != "run_live_api_tests.py":
        raise SystemExit("ERROR: live API report must be generated by run_live_api_tests.py")
    requests_path = Path(str(report.get("requestConfigPath") or "")).resolve()
    failures = []
    if not requests_path.is_file() or report.get("requestConfigHash") != sha256(requests_path):
        failures.append("stale live API request config")
    if report.get("apiContractHash") != sha256(contract_path):
        failures.append("stale live API contract")
    if report.get("runtimeManifestHash") != sha256(runtime_path):
        failures.append("stale live API runtime manifest")
    if report.get("ok") is not True:
        failures.append("live API runner report is not successful")
    if failures:
        raise SystemExit("ERROR: live API evidence failed:\n" + "\n".join(failures))
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    runtime = json.loads(runtime_path.read_text(encoding="utf-8"))
    try:
        current = execute_operations(
            contract,
            runtime,
            json.loads(requests_path.read_text(encoding="utf-8")),
            str(report.get("baseUrl") or ""),
            args.timeout,
        )
    except ValueError as error:
        raise SystemExit(f"ERROR: live API evidence HTTP recheck failed: {error}") from error
    expected_ids = [str(operation.get("id") or "") for operation in runtime.get("operations") or []]
    if report.get("checkedOperations") != expected_ids:
        failures.append("live API checked operation closure differs")
    failed = [result["id"] for result in current if not result["ok"]]
    if failed:
        failures.append(f"current live API HTTP checks failed: {failed}")
    if failures:
        raise SystemExit("ERROR: live API evidence failed:\n" + "\n".join(failures))
    print(f"ok live API evidence operations={len(current)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
