#!/usr/bin/env python3
"""Generate a deterministic Flutter widget test that traces the REAL render of the on-line page.

Invariant ③ requires comparing the real component render (bbox/token/text per node) against the
design-derived render_plan — NOT a golden image, NOT the model's eyeballing. To get the *real*
geometry we pump the actual page (fed the SAME fixture) in a widget test sized to the design
artboard (u=1, so logical px == design px) and, for every node carrying `ValueKey('iff:<id>')`,
record `tester.getRect` plus the rendered Text/Decoration style. The emitted JSON
(`actual_layout_trace.json`) is then diffed by `check_render_fidelity.py`.

The node id list + artboard dimensions come from `generate_canvas`'s `*.expected.json` sidecar, so
the trace covers exactly the keyed (placed) nodes. The test is fully generated (no hand edits):
the page-under-test is parameterised so the same harness works for the home canvas and for any
data-driven component page that mounts the keyed primitives.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

TEMPLATE = r"""// GENERATED by iFF gen_layout_trace_test.py — DO NOT EDIT BY HAND.
// 真实渲染 layout trace:按设计画板尺寸 pump 真实页面(u=1,逻辑像素==设计像素),
// 对每个挂了 ValueKey('iff:<id>') 的节点记录 getRect + 文本/装饰样式,写出
// actual_layout_trace.json 供 check_render_fidelity.py 逐组件比对 render_plan。
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
__PAGE_IMPORT__
__EXTRA_IMPORTS__
void main() {
  testWidgets('iff layout trace (real render vs render_plan)', (WidgetTester tester) async {
    const double dw = __DW__;
    const double dh = __DH__;
    tester.view.physicalSize = const Size(dw, dh);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(() {
      tester.view.resetPhysicalSize();
      tester.view.resetDevicePixelRatio();
    });

    await tester.pumpWidget(MaterialApp(
      debugShowCheckedModeBanner: false,
      home: __PAGE_EXPR__,
    ));
    // 必须 trace 真实上线页(不变量②⑥:验收对象==上线对象),页面常异步加载数据后才
    // 挂出可见层 —— 喂同源设计 fixture 时 Future 在下一个 microtask 完成,连泵几帧让它
    // 渲染到位(同时把无真机图片字节的 asset 解码异常排掉,固定尺寸几何不受影响)。
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 350));
    await tester.pump(const Duration(seconds: 1));
    while (tester.takeException() != null) {}

    const List<String> ids = <String>[__IDS__];
    final Map<String, dynamic> nodes = <String, dynamic>{};

    Offset pageOrigin = Offset.zero;
    final Finder pageFinder = find.byType(__PAGE_TYPE__);
    if (pageFinder.evaluate().isNotEmpty) {
      pageOrigin = tester.getRect(pageFinder.first).topLeft;
    }

    for (final String id in ids) {
      final Finder f = find.byKey(ValueKey<String>('iff:$id'));
      if (f.evaluate().isEmpty) {
        nodes[id] = <String, dynamic>{'present': false};
        continue;
      }
      final Rect r = tester.getRect(f.first);
      final Map<String, dynamic> rec = <String, dynamic>{
        'present': true,
        'bbox': <double>[
          r.left - pageOrigin.dx,
          r.top - pageOrigin.dy,
          r.width,
          r.height,
        ],
      };
      final Finder tf = find.descendant(of: f.first, matching: find.byType(Text));
      if (tf.evaluate().isNotEmpty) {
        final Text t = tester.widget<Text>(tf.first);
        rec['fontSize'] = t.style?.fontSize;
        rec['colorArgb'] = t.style?.color?.toARGB32();
        rec['text'] = t.data ?? t.textSpan?.toPlainText();
      }
      final Finder df = find.descendant(of: f.first, matching: find.byType(DecoratedBox));
      if (df.evaluate().isNotEmpty) {
        final DecoratedBox d = tester.widget<DecoratedBox>(df.first);
        final Decoration dec = d.decoration;
        if (dec is BoxDecoration) {
          if (dec.color != null) rec['colorArgb'] = dec.color!.toARGB32();
          final BorderRadiusGeometry? br = dec.borderRadius;
          if (br is BorderRadius) rec['radius'] = br.topLeft.x;
        } else if (dec is ShapeDecoration) {
          if (dec.color != null) rec['colorArgb'] = dec.color!.toARGB32();
        }
      }
      nodes[id] = rec;
    }

    final File out = File(r'__TRACE_OUT__');
    out.parent.createSync(recursive: true);
    out.writeAsStringSync(const JsonEncoder.withIndent('  ')
        .convert(<String, dynamic>{'pageType': '__PAGE_TYPE_STR__', 'nodes': nodes}));
    // 至少要找到一个节点,否则页面根本没渲染(0x0 collapse / 路由错挂)——直接失败。
    final int present =
        nodes.values.where((dynamic v) => (v as Map)['present'] == true).length;
    expect(present, greaterThan(0),
        reason: 'no keyed iff node rendered — page collapsed or wrong page mounted');
  });
}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--expected", required=True, help="generate_canvas *.expected.json sidecar")
    ap.add_argument("--page-import", required=True,
                    help="dart import line target, e.g. package:app/features/home/presentation/home_page.dart")
    ap.add_argument("--page-type", required=True, help="widget class under test, e.g. HomeArtboardCanvas")
    ap.add_argument("--page-expr", help="widget expr to pump as the REAL on-line page, injecting the "
                    "same-source design fixture, e.g. \"HomePage(repository: MockHomeRepository.design())\" "
                    "(default: '<PageType>()'). Trace the real page, not the canvas in isolation, so "
                    "page-level wrapping bugs (SafeArea offset, Stack collapse) are caught.")
    ap.add_argument("--extra-imports", default="",
                    help="comma-separated extra dart imports the page-expr needs (repository/fixture)")
    ap.add_argument("--trace-out", required=True, help="absolute path the test writes the trace JSON to")
    ap.add_argument("--out", required=True, help="generated *_layout_trace_test.dart path")
    a = ap.parse_args()

    expected = json.loads(Path(a.expected).read_text(encoding="utf-8"))
    ids = list(expected.get("nodes", {}).keys())
    dw = expected.get("artboardWidth") or 750.0
    dh = expected.get("artboardHeight") or 5874.0
    page_expr = a.page_expr or f"{a.page_type}()"
    extra = "".join(f"import '{p.strip()}';\n" for p in a.extra_imports.split(",") if p.strip())

    ids_dart = ", ".join(f"'{i}'" for i in ids)
    dart = (TEMPLATE
            .replace("__PAGE_IMPORT__", f"import '{a.page_import}';")
            .replace("__EXTRA_IMPORTS__", extra)
            .replace("__DW__", repr(float(dw)))
            .replace("__DH__", repr(float(dh)))
            .replace("__PAGE_EXPR__", page_expr)
            .replace("__PAGE_TYPE_STR__", a.page_type)
            .replace("__PAGE_TYPE__", a.page_type)
            .replace("__IDS__", ids_dart)
            .replace("__TRACE_OUT__", a.trace_out))

    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dart, encoding="utf-8")
    print(json.dumps({"out": str(out), "ids": len(ids), "designWidth": dw, "designHeight": dh,
                      "traceOut": a.trace_out}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
