#!/usr/bin/env python3
"""Deterministic render_plan.json -> responsive Flutter UI compiler (关系换算).

Emits, per the project implementation rules (see iFF/implementation_rules.md):
  - lib/<feature>/.../app_colors.dart   : centralized color tokens (IMPL-TOKEN)
  - the home artboard widget            : a RESPONSIVE canvas where every size /
    position is `设计像素 * u`, with `u = LayoutBuilder.maxWidth / 设计宽度`
    (关系换算, IMPL-LAYOUT-1). At a 375pt-wide device u=0.5 (i.e. design px ÷2,
    IMPL-UNIT-2); it scales proportionally on any width. Rendering the same code
    at width=设计宽度 reproduces the design 1:1 for the visual QA gate.

Why a script (deterministic): canvas emission from render_plan is fully
deterministic; leaving it to the model made fidelity non-reproducible and forced
re-discovering the boolean-operand overdraw / font / flip bugs every run.

NOTE: `TextStyle.height` is never emitted (IMPL-LAYOUT-4). Colors never appear
inline (IMPL-TOKEN-1) — they go through `AppColors`. The build is split into
per-band region widgets to avoid one huge build method (IMPL-COMP-1).
"""
from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

BOOL_KW = re.compile(r"subtract|union|intersect|exclude|boolean", re.I)
SKIP_IMPL = {"covered_by_asset", "covered_by_text", "hidden"}
ASSET_IMPL = {"image_png", "image_webp", "svg", "asset", "image", "image_fill"}


# ---------------------------------------------------------------- color tokens
class ColorRegistry:
    """Collects every distinct color used and hands back an `AppColors.cXXXX`
    reference, so no `Color(0x..)` ever appears inline in widget code."""

    def __init__(self) -> None:
        self.colors: dict[int, str] = {}

    def ref(self, argb: int) -> str:
        argb &= 0xFFFFFFFF
        name = f"c{argb:08X}"
        self.colors[argb] = name
        return f"AppColors.{name}"

    def emit_dart(self) -> str:
        lines = [
            "// GENERATED by iFF generate_canvas.py — DO NOT EDIT BY HAND.",
            "// 设计稿用到的全部颜色 token,集中管理(IMPL-TOKEN-1)。",
            "// 命名 c<AARRGGBB> 为确定性生成;如需语义命名请在此文件统一重命名后全局替换。",
            "import 'package:flutter/material.dart';",
            "",
            "abstract final class AppColors {",
        ]
        for argb in sorted(self.colors):
            lines.append(f"  static const Color {self.colors[argb]} = Color(0x{argb:08X});")
        lines.append("}")
        return "\n".join(lines) + "\n"


def hex_to_argb_int(h: str, opacity: float = 1.0) -> int:
    if not h:
        return 0
    h = h.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) == 6:
        a, r, g, b = 255, int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    elif len(h) == 8:
        r, g, b, a = (int(h[i:i + 2], 16) for i in (0, 2, 4, 6))
    else:
        return 0
    a = max(0, min(255, round(a * opacity)))
    return (a << 24) | (r << 16) | (g << 8) | b


def rgba_dict_argb(c, opacity: float = 1.0) -> int | None:
    if not isinstance(c, dict):
        return None
    r = round(c.get("r", 0) * 255)
    g = round(c.get("g", 0) * 255)
    b = round(c.get("b", 0) * 255)
    a = max(0, min(255, round(c.get("a", 1) * 255 * opacity)))
    return (a << 24) | (r << 16) | (g << 8) | b


# --------------------------------------------------------------- value helpers
def m(v: float) -> str:
    """A length expressed via 关系换算: 设计像素 * 响应单位 u (IMPL-LAYOUT-1)."""
    return f"{v:.2f} * u"


def weight_to_flutter(w) -> str:
    try:
        w = int(round(float(w) / 100.0)) * 100
    except (TypeError, ValueError):
        w = 400
    return f"FontWeight.w{max(100, min(900, w))}"


def radius_value(radius):
    if not isinstance(radius, dict):
        return 0.0
    return max(radius.get(k, 0) or 0 for k in ("topLeft", "topRight", "bottomLeft", "bottomRight"))


def radius_expr(radius) -> str | None:
    if not isinstance(radius, dict):
        return None
    tl, tr = radius.get("topLeft", 0) or 0, radius.get("topRight", 0) or 0
    bl, br = radius.get("bottomLeft", 0) or 0, radius.get("bottomRight", 0) or 0
    if not any((tl, tr, bl, br)):
        return None
    return (f"BorderRadius.only(topLeft: Radius.circular({m(tl)}), topRight: Radius.circular({m(tr)}), "
            f"bottomLeft: Radius.circular({m(bl)}), bottomRight: Radius.circular({m(br)}))")


def gradient_expr(gradient_fills, reg: ColorRegistry) -> str | None:
    if not gradient_fills:
        return None
    g = gradient_fills[0].get("gradient") if isinstance(gradient_fills[0], dict) else None
    if not g:
        return None
    stops = g.get("stops") or []
    if len(stops) < 2:
        return None
    colors, positions = [], []
    for s in stops:
        argb = rgba_dict_argb(s.get("color", {}))
        if argb is None:
            return None
        colors.append(reg.ref(argb))
        positions.append(f"{s.get('position', 0):.4f}")
    frm, to = g.get("from", {}), g.get("to", {})
    bx, by = 2 * frm.get("x", 0.0) - 1, 2 * frm.get("y", 0.0) - 1
    ex, ey = 2 * to.get("x", 1.0) - 1, 2 * to.get("y", 0.0) - 1
    cols = ", ".join(colors)
    pos = ", ".join(positions)
    if g.get("type", 0) == 2:
        return f"RadialGradient(colors: [{cols}], stops: const [{pos}])"
    return (f"LinearGradient(begin: Alignment({bx:.4f}, {by:.4f}), end: Alignment({ex:.4f}, {ey:.4f}), "
            f"colors: [{cols}], stops: const [{pos}])")


def border_expr(border, reg: ColorRegistry):
    strokes = border if isinstance(border, list) else ([border] if isinstance(border, dict) else [])
    for s in strokes:
        if not isinstance(s, dict) or not s.get("isEnabled", True):
            continue
        w = s.get("width") or s.get("weight") or 0
        if not w:
            continue
        argb = rgba_dict_argb(s.get("color"))
        if argb is None:
            continue
        return f"Border.all(color: {reg.ref(argb)}, width: {m(float(w))})"
    return None


def shadow_expr(shadow, reg: ColorRegistry) -> str | None:
    shadows = shadow if isinstance(shadow, list) else ([shadow] if isinstance(shadow, dict) else [])
    parts = []
    for s in shadows:
        if not isinstance(s, dict):
            continue
        argb = rgba_dict_argb(s.get("color")) or 0x33000000
        ox = s.get("offsetX", s.get("x", 0)) or 0
        oy = s.get("offsetY", s.get("y", 0)) or 0
        blur = s.get("blur", s.get("radius", 0)) or 0
        spread = s.get("spread", 0) or 0
        parts.append(f"BoxShadow(color: {reg.ref(argb)}, offset: Offset({m(ox)}, {m(oy)}), "
                     f"blurRadius: {m(blur)}, spreadRadius: {m(spread)})")
    return f"[{', '.join(parts)}]" if parts else None


def is_boolean_operand(path: str) -> bool:
    segs = (path or "").split("/")
    return any(BOOL_KW.search(seg) for seg in segs[:-1])


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("$", "\\$")


def fill_hex(node) -> str | None:
    fills = node.get("fills") or []
    if fills and isinstance(fills[0], str) and fills[0].startswith("#"):
        return fills[0]
    return None


def effective_radius(node: dict, nodes: dict):
    rad = node.get("radius")
    if isinstance(rad, dict) and radius_value(rad):
        return rad
    for cid in node.get("children") or []:
        crad = (nodes.get(cid) or {}).get("radius")
        if isinstance(crad, dict) and radius_value(crad):
            return crad
    return rad


def ellipse_holes(node: dict, nodes: dict, ox: float, oy: float):
    holes = []
    for cid in node.get("children") or []:
        child = nodes.get(cid)
        if not child or (child.get("shapeType") or "").lower() not in ("ellipse", "oval"):
            continue
        cb = child.get("bbox")
        if cb and len(cb) == 4:
            holes.append((cb[0] - ox, cb[1] - oy, cb[2], cb[3]))
    return holes


ALIGN_MAP = {"center": "TextAlign.center", "right": "TextAlign.right",
             "justified": "TextAlign.justify", "justify": "TextAlign.justify"}


def emit_text(node, x, y, w, h, reg: ColorRegistry, pos, end, nid: str, slot_ids: set) -> str:
    txt = esc(str(node.get("text", "")))
    size = node.get("fontSize") or 14
    base_argb = hex_to_argb_int(fill_hex(node) or "#000000")
    wt = weight_to_flutter(node.get("weight"))
    ls = node.get("letterSpacing") or {}
    ls_val = ls.get("value", 0) if isinstance(ls, dict) else 0
    ls_expr = f", letterSpacing: {m(float(ls_val))}" if ls_val else ""
    align = (node.get("align") or "left").lower()
    valign = (node.get("verticalAlignment") or "top").lower()
    text_align = ALIGN_MAP.get(align, "TextAlign.left")

    # 字号同样走关系换算(IMPL-LAYOUT-1);严禁 TextStyle.height(IMPL-LAYOUT-4)。
    runs = node.get("textRuns") or []
    distinct = {json.dumps(r.get("color") or (r.get("font") or {}).get("color"), sort_keys=True) for r in runs}
    if len(runs) > 1 and len(distinct) > 1:
        spans = []
        for r in runs:
            rc = rgba_dict_argb(r.get("color") or (r.get("font") or {}).get("color")) or base_argb
            rsize = (r.get("font") or {}).get("size") or size
            spans.append(f"TextSpan(text: '{esc(str(r.get('content', '')))}', style: TextStyle("
                         f"fontFamily: 'SF Pro Text', fontSize: {m(float(rsize))}, fontWeight: {wt}, "
                         f"color: {reg.ref(rc)}))")
        inner = f"Text.rich(TextSpan(children: [{', '.join(spans)}]), textAlign: {text_align}, softWrap: true)"
    else:
        # 动态文本槽:从注入的 slotText 取值,缺省回退设计展示值(不变量①④⑦);静态文案保持字面量。
        txt_arg = f"slotText['{nid}'] ?? '{txt}'" if nid in slot_ids else f"'{txt}'"
        inner = (f"Text({txt_arg}, textAlign: {text_align}, softWrap: true, overflow: TextOverflow.visible, "
                 f"style: TextStyle(fontFamily: 'SF Pro Text', fontSize: {m(float(size))}, "
                 f"fontWeight: {wt}, color: {reg.ref(base_argb)}{ls_expr}))")

    box_align = {"center": "Alignment.topCenter", "right": "Alignment.topRight"}.get(align, "Alignment.topLeft")
    if valign == "center":
        box_align = {"center": "Alignment.center", "right": "Alignment.centerRight"}.get(align, "Alignment.centerLeft")
    elif valign == "bottom":
        box_align = {"center": "Alignment.bottomCenter", "right": "Alignment.bottomRight"}.get(align, "Alignment.bottomLeft")
    return pos + f"Align(alignment: {box_align}, child: SizedBox(width: {m(w)}, child: {inner}))" + end


def emit_node(node: dict, asset_prefix: str, nodes: dict, reg: ColorRegistry, artboard_origin, nid: str, placed: dict, slot_ids: set) -> str | None:
    impl = node.get("implementation")
    if impl in SKIP_IMPL or is_boolean_operand(node.get("path", "")):
        return None
    bbox = node.get("bbox")
    if not bbox or len(bbox) != 4:
        return None
    x, y, w, h = bbox
    if w <= 0 or h <= 0:
        return None
    if node.get("parent") is None:
        x, y = 0.0, 0.0

    rot = node.get("rotation") or 0
    # absoluteTransform 是定位权威:无旋转(b==c==0)但有翻转(a<0/d<0)时,bbox 原点
    # 落在翻转边,需用变换后的角点重算真实 AABB(切图已是最终朝向,翻转仅是位置)。
    at = node.get("absoluteTransform")
    if (at and len(at) == 2 and abs(at[0][1]) < 1e-6 and abs(at[1][0]) < 1e-6
            and (at[0][0] < 0 or at[1][1] < 0)):
        a, _, tx = at[0]
        _, d, ty = at[1]
        ox, oy = artboard_origin
        x = min(a * 0.0 + tx - ox, a * w + tx - ox)
        y = min(d * 0.0 + ty - oy, d * h + ty - oy)
        rot = 0
    if impl in ASSET_IMPL:
        rot = 0  # 切图为预渲染最终朝向,不再旋转

    # 记录脚本为该节点最终落位的归一化几何(已减画板原点 / 处理翻转),作为
    # check_render_fidelity 的「设计期望」基准——真实渲染 getRect 须与此一致。
    placed[nid] = [round(float(x), 2), round(float(y), 2), round(float(w), 2), round(float(h), 2)]

    rot_pre, rot_post = "", ""
    if abs(rot) > 0.5:
        rot_pre = f"Transform.rotate(angle: {-math.radians(rot):.5f}, child: "
        rot_post = ")"
    # 每个可见节点挂 ValueKey('iff:<节点id>'),让真实渲染可被 layout trace 按节点回溯
    # (IMPL 不变量③:真实组件渲染 bbox/token vs render_plan 逐组件 diff 的前提)。
    key_open = f"KeyedSubtree(key: const ValueKey('iff:{nid}'), child: "
    pos = f"Positioned(left: {m(x)}, top: {m(y)}, width: {m(w)}, height: {m(h)}, child: " + key_open + rot_pre
    end = rot_post + "))"

    if impl == "text":
        return emit_text(node, x, y, w, h, reg, pos, end, nid, slot_ids)

    if impl in ASSET_IMPL:
        asset = node.get("asset")
        if not asset:
            return None
        return pos + f"Image.asset('{asset_prefix}{Path(asset).name}', fit: BoxFit.fill)" + end

    name = node.get("name") or ""
    if name.startswith("Star") and fill_hex(node) == "#000000":
        return pos + f"CustomPaint(painter: const _SparkleStarPainter())" + end

    grad = gradient_expr(node.get("gradientFills"), reg)
    hexc = fill_hex(node)
    opacity = node.get("opacity", 1) or 1
    deco = []
    if grad:
        deco.append(f"gradient: {grad}")
    elif hexc:
        deco.append(f"color: {reg.ref(hex_to_argb_int(hexc, opacity))}")
    b = border_expr(node.get("border"), reg)
    if b:
        deco.append(f"border: {b}")
    sh = shadow_expr(node.get("shadow") or node.get("effects"), reg)
    if sh:
        deco.append(f"boxShadow: {sh}")

    if impl == "oval_shape":
        if not deco:
            return None
        return pos + f"Container(decoration: ShapeDecoration(shape: const OvalBorder(), {', '.join(deco)}))" + end

    # boolean-subtract + 椭圆操作数 = 圆角矩形挖椭圆洞,露出底层装饰(角部 leaf)。
    holes = ellipse_holes(node, nodes, x, y)
    if holes and hexc and not grad:
        r = radius_value(effective_radius(node, nodes))
        hole_list = ", ".join(f"Rect.fromLTWH({m(hx)}, {m(hy)}, {m(hw)}, {m(hh)})" for hx, hy, hw, hh in holes)
        return (pos + f"_PunchedRect(color: {reg.ref(hex_to_argb_int(hexc, opacity))}, "
                f"radius: {m(r)}, holes: [{hole_list}])" + end)

    rad = radius_expr(effective_radius(node, nodes))
    if rad:
        deco.append(f"borderRadius: {rad}")
    if not deco:
        return None
    return pos + f"Container(decoration: BoxDecoration({', '.join(deco)}))" + end


# ----------------------------------------------------------------- band layout
# 把节点按设计纵向分区拆成独立 region widget,避免单个超大 build(IMPL-COMP-1)。
BANDS = [
    ("Header", "顶部:状态栏 / 问候语 / 客服入口", 0, 255),
    ("Cards", "贷款状态卡片区(12 个状态)", 255, 4960),
    ("Support", "客服服务区", 4960, 5660),
    ("TabBar", "底部 Tab 栏", 5660, 10_000_000),
]


def band_of(y_center: float) -> str:
    for name, _desc, lo, hi in BANDS:
        if lo <= y_center < hi:
            return name
    return "Cards"


# ----------------------------------------------------------------- z 序 / 系统 UI
# 背景铺底形状(整宽或越出画板顶部、低 z 的渐变/形状)必须画在所有 band 之下。
# band 按 y 中心分层会丢全局 z 顺序,导致铺底块盖住头部内容,故单独沉到底层。
BACKDROP_IMPL = {"shape", "gradient_shape", "oval_shape", "vector_shape", "shape_container", "image_fill"}

# 系统状态栏(电量/Wi-Fi/信号/时间)是手机系统 UI,按 IMPL-IMG-3 不实现、不绘制。
_STATUS_MARKERS = ("battery", "wifi", "mobile signal", "cellular")


def status_bar_node_ids(nodes: dict, artboard_width: float) -> set:
    """识别系统状态栏整棵子树并返回其节点 id 集合。判据:子孙节点命名命中
    电量/Wi-Fi/信号,且其所属顶层 frame 是「画板顶部 + 近满宽 + 矮条」(iOS 状态栏
    几何),避免误删同名业务节点。"""
    candidate_paths = set()
    for n in nodes.values():
        nm = (n.get("name") or "").strip().lower()
        if any(m in nm for m in _STATUS_MARKERS):
            parts = (n.get("path") or "").split("/")
            if len(parts) >= 2:
                candidate_paths.add("/".join(parts[:2]))
    frame_paths = set()
    for n in nodes.values():
        if (n.get("path") or "") in candidate_paths:
            bb = n.get("bbox") or [0, 0, 0, 0]
            if bb[1] < 50 and bb[2] >= 0.8 * artboard_width and bb[3] <= 120:
                frame_paths.add(n["path"])
    ids = set()
    for nid, n in nodes.items():
        p = n.get("path") or ""
        if any(p == fp or p.startswith(fp + "/") for fp in frame_paths):
            ids.add(nid)
    return ids


_STAR_PAINTER_SRC = """
/// 四角星(sparkle):设计为无切图的矢量黑星,这里按几何绘制(IMPL-IMG 缺图兜底)。
class _SparkleStarPainter extends CustomPainter {
  const _SparkleStarPainter({this.color = const Color(0xFF000000)});
  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    final double cx = size.width / 2, cy = size.height / 2;
    final double ro = math.min(cx, cy), ri = ro * 0.36;
    final Path p = Path();
    for (int i = 0; i < 8; i++) {
      final double r = i.isEven ? ro : ri;
      final double angle = -math.pi / 2 + i * math.pi / 4;
      final double px = cx + r * math.cos(angle), py = cy + r * math.sin(angle);
      i == 0 ? p.moveTo(px, py) : p.lineTo(px, py);
    }
    p.close();
    canvas.drawPath(p, Paint()..color = color..isAntiAlias = true);
  }

  @override
  bool shouldRepaint(covariant _SparkleStarPainter oldDelegate) => oldDelegate.color != color;
}
"""

_PUNCHED_PAINTER_SRC = """
/// 圆角矩形挖椭圆洞:还原 Figma boolean-subtract(露出底层装饰,如卡片角部 leaf)。
class _PunchedRect extends StatelessWidget {
  const _PunchedRect({super.key, required this.color, required this.radius, required this.holes});

  final Color color;
  final double radius;
  final List<Rect> holes;

  @override
  Widget build(BuildContext context) {
    return CustomPaint(painter: __PunchedRectPainter(color: color, radius: radius, holes: holes));
  }
}

class __PunchedRectPainter extends CustomPainter {
  const __PunchedRectPainter({required this.color, required this.radius, required this.holes});

  final Color color;
  final double radius;
  final List<Rect> holes;

  @override
  void paint(Canvas canvas, Size size) {
    Path path = Path()
      ..addRRect(RRect.fromRectAndRadius(Offset.zero & size, Radius.circular(radius)));
    for (final Rect hole in holes) {
      path = Path.combine(PathOperation.difference, path, Path()..addOval(hole));
    }
    canvas.drawPath(path, Paint()..color = color..isAntiAlias = true);
  }

  @override
  bool shouldRepaint(covariant __PunchedRectPainter oldDelegate) => false;
}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--render-plan", required=True)
    ap.add_argument("--out", required=True, help="home artboard widget .dart path")
    ap.add_argument("--colors-out", help="app_colors.dart path (default: alongside --out)")
    ap.add_argument("--colors-import", default="app_colors.dart")
    ap.add_argument("--asset-prefix", default="assets/images/")
    ap.add_argument("--classification", help="design_classification.json — authoritative artboard dims")
    ap.add_argument("--component-manifest", help="component_manifest.json — dynamic_text_slot node ids become data-driven")
    ap.add_argument("--class-name", default="HomeArtboardCanvas",
                    help="visible-layer widget class name; give distinct names per state so a multi-state "
                         "feature's canvases don't collide (e.g. InformationListCanvas / InformationEmptyCanvas)")
    ap.add_argument("--artboard-width", type=float, default=750.0)
    ap.add_argument("--artboard-height", type=float, default=5874.0)
    a = ap.parse_args()

    # 画板尺寸以设计分类为准(不同设计稿高度不同);只有未提供 classification 时才用默认值,
    # 避免把某一稿的高度(如旧 5874)写死到所有稿。
    if a.classification and Path(a.classification).is_file():
        art = json.loads(Path(a.classification).read_text()).get("artboard") or {}
        if art.get("width"):
            a.artboard_width = float(art["width"])
        if art.get("height"):
            a.artboard_height = float(art["height"])

    rp = json.loads(Path(a.render_plan).read_text())
    nodes = rp["nodes"]

    # 动态文本槽节点 id:这些 text 节点的展示值由注入的 slotText 决定(数据驱动),
    # 其余文案保持字面量(静态 chrome)。来源 component_manifest.dynamicSlots(不变量①④)。
    slot_ids: set = set()
    if a.component_manifest and Path(a.component_manifest).is_file():
        cm = json.loads(Path(a.component_manifest).read_text())
        for comp in cm.get("components", []):
            for s in comp.get("dynamicSlots", []) or []:
                if s.get("node"):
                    slot_ids.add(s["node"])
    artboard_origin = (0.0, 0.0)
    artboard_root_id = None
    for nid, n in nodes.items():
        if n.get("parent") is None:
            artboard_root_id = nid
            if n.get("bbox"):
                artboard_origin = (n["bbox"][0], n["bbox"][1])
            break

    order = list(nodes.keys())  # 插入顺序 = 设计 z 顺序
    first_text_idx = next(
        (i for i, k in enumerate(order) if nodes[k].get("implementation") == "text"),
        len(order),
    )
    chrome_ids = status_bar_node_ids(nodes, a.artboard_width)

    def is_backdrop(node: dict, idx: int) -> bool:
        # 整宽或越出画板顶部、且排在首个文字之前的画板级铺底形状 -> 沉到底层。
        if node.get("parent") != artboard_root_id:
            return False
        if node.get("implementation") not in BACKDROP_IMPL:
            return False
        bb = node.get("bbox") or [0, 0, 0, 0]
        return (bb[2] >= 0.6 * a.artboard_width or bb[1] < 0) and idx < first_text_idx

    reg = ColorRegistry()
    band_widgets: dict[str, list[str]] = {name: [] for name, *_ in BANDS}
    root_base = []
    placed: dict = {}  # nid -> 脚本落位的归一化几何(expected.json 基准)
    painted = skipped = chrome = 0
    for idx, (nid, node) in enumerate(nodes.items()):
        if nid in chrome_ids:  # IMPL-IMG-3:系统状态栏不绘制
            chrome += 1
            continue
        widget = emit_node(node, a.asset_prefix, nodes, reg, artboard_origin, nid, placed, slot_ids)
        if widget is None:
            skipped += 1
            placed.pop(nid, None)
            continue
        painted += 1
        bbox = node["bbox"]
        if node.get("parent") is None or is_backdrop(node, idx):
            root_base.append("        " + widget + ",")
        else:
            band_widgets[band_of(bbox[1] + bbox[3] / 2.0)].append("        " + widget + ",")

    # per-band region widgets
    band_classes = []
    band_children = []
    for name, desc, *_ in BANDS:
        body = "\n".join(band_widgets[name]) or "        // (本区无可见节点)"
        band_classes.append(f"""
/// {desc}。
class _Home{name} extends StatelessWidget {{
  const _Home{name}({{required this.u, required this.slotText}});

  /// u:关系换算响应单位 = 屏宽 / 设计宽度(IMPL-LAYOUT-1)。
  final double u;

  /// 动态文本槽取值(节点id -> 展示值);上层用同源 fixture / 真实 DTO 注入,
  /// 缺省回退到设计稿展示值,保证数据未到位时仍逐像素还原(IMPL-DATA / 不变量①⑦)。
  final Map<String, String> slotText;

  @override
  Widget build(BuildContext context) {{
    return Stack(
      clipBehavior: Clip.none,
      children: <Widget>[
{body}
      ],
    );
  }}
}}""")
        band_children.append(f"          Positioned.fill(child: _Home{name}(u: u, slotText: slotText)),")

    base_body = "\n".join(root_base) or "        // (无根背景)"
    rel_import = a.colors_import

    # 矢量装饰画笔(四角星 / boolean-subtract 挖洞)是 file-private 的,只在本稿真正用到时
    # 才输出——否则多状态特性里没用到它们的画布会触发 unused_element 警告(IMPL-STYLE-5 要求
    # analyze 干净)。用法从已生成的可见层代码探测。
    _widget_src = base_body + "".join(band_classes)
    used_star = "_SparkleStarPainter(" in _widget_src
    used_punched = "_PunchedRect(" in _widget_src
    painters = (_STAR_PAINTER_SRC if used_star else "") + (_PUNCHED_PAINTER_SRC if used_punched else "")
    # dart:math 只被 sparkle star 画笔用到(旋转角已在 Python 侧算成字面量);未用到就不导入,
    # 否则 analyze 报 unused_import。
    math_import = "import 'dart:math' as math;\n" if used_star else ""

    dart = f"""// GENERATED by iFF generate_canvas.py — DO NOT EDIT BY HAND.
// 关系换算响应式还原:每个尺寸/位置都是「设计像素 * u」,u 随屏宽自适应。
// 渲染在设计宽度时 1:1 还原设计稿(供视觉 QA);在真机按比例缩放。
// 节点:{painted} 个绘制 / {skipped} 个跳过(覆盖/隐藏/boolean)/ {chrome} 个系统状态栏排除。
{math_import}import 'package:flutter/material.dart';

import '{rel_import}';

/// 首页设计稿响应式画布(数据驱动可见层本体,不是静态 golden)。整张稿按设计宽度等比
/// 映射到当前屏宽;几何/样式由脚本从 render_plan/tokens 喂入,动态文本由 [slotText] 注入。
class {a.class_name} extends StatelessWidget {{
  const {a.class_name}({{super.key, this.slotText = const <String, String>{{}}}});

  /// 动态文本槽取值(节点id -> 展示值)。同源 fixture / 真实 DTO 经此注入;
  /// 缺省回退设计稿展示值(不变量①④⑦:可见层数据驱动、切数据即变、fixture 源自设计)。
  final Map<String, String> slotText;

  /// 设计稿原始宽高(像素)。仅用于推导响应单位 u,是关系换算的唯一基准,
  /// 不作为任何控件的固定尺寸(IMPL-LAYOUT-2)。
  static const double designWidth = {a.artboard_width};
  static const double designHeight = {a.artboard_height};

  @override
  Widget build(BuildContext context) {{
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {{
        // 关系换算基准单位:把设计像素映射到当前可用宽度。375pt 宽时 u=0.5
        // (即设计像素÷2,IMPL-UNIT-2),更宽屏按比例放大,保证多屏一致。
        final double u = constraints.maxWidth / designWidth;
        return SingleChildScrollView(
          child: SizedBox(
            width: constraints.maxWidth,
            height: designHeight * u,
            child: Stack(
              clipBehavior: Clip.hardEdge,
              children: <Widget>[
{base_body}
{chr(10).join(band_children)}
              ],
            ),
          ),
        );
      }},
    );
  }}
}}

{painters}{''.join(band_classes)}
"""
    out = Path(a.out)
    out.write_text(dart)
    colors_out = Path(a.colors_out) if a.colors_out else out.with_name(a.colors_import)
    # 多状态特性会就同一 colors 文件多次调用本脚本;颜色 token 名是确定性的 c<AARRGGBB>,
    # 所以合并 = 按 argb 取并集,绝不互相覆盖(否则 worker 得手动合并多份 app_colors)。
    if colors_out.is_file():
        for m_argb in re.findall(r"Color\(0x([0-9A-Fa-f]{8})\)", colors_out.read_text(encoding="utf-8")):
            argb = int(m_argb, 16)
            reg.colors.setdefault(argb, f"c{argb:08X}")
    colors_out.write_text(reg.emit_dart())

    # 设计期望 sidecar:每个落位节点的归一化几何 + 设计样式(颜色/字号/文案/圆角),
    # 全部源自 render_plan(设计真值),供 check_render_fidelity 与真实渲染 trace 逐组件比对。
    expected = {}
    for nid in placed:
        node = nodes[nid]
        is_text = node.get("implementation") == "text"
        expected[nid] = {
            "bbox": placed[nid],
            "impl": node.get("implementation"),
            "text": node.get("text") if is_text else None,
            "fontSize": node.get("fontSize") if is_text else None,
            "weight": node.get("weight") if is_text else None,
            "colorHex": fill_hex(node),
            "radius": radius_value(effective_radius(node, nodes)),
        }
    expected_out = Path(str(out) + ".expected.json")
    expected_out.write_text(json.dumps(
        {"artboardWidth": a.artboard_width, "artboardHeight": a.artboard_height, "nodes": expected},
        ensure_ascii=False, indent=2))

    # 设计种子 fixture:动态槽节点 id -> 设计稿展示值(不变量⑦)。同源 fixture 的默认内容就是它;
    # 真实 repository/DTO 用真接口字段覆盖这些键(不变量④),覆盖同值时可见层零变化。
    slot_seed = {nid: nodes[nid].get("text", "") for nid in placed
                 if nid in slot_ids and nodes[nid].get("implementation") == "text"}
    slots_out = Path(str(out) + ".slots.json")
    slots_out.write_text(json.dumps(slot_seed, ensure_ascii=False, indent=2))

    print(json.dumps({"out": str(out), "colors": str(colors_out), "expected": str(expected_out),
                      "slots": str(slots_out), "slotCount": len(slot_seed),
                      "painted": painted, "skipped": skipped, "tokens": len(reg.colors)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
