#!/usr/bin/env python3
"""Generate the deterministic smoke test for one iFF shared widget."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


PACKAGE_NAME_RE = re.compile(r"[a-z][a-z0-9_]*\Z")
CLASS_NAME_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


def project_path(project: Path, value: str) -> Path:
    path = Path(value)
    return path.resolve() if path.is_absolute() else (project / path).resolve()


def read_package_name(pubspec: Path) -> str:
    if not pubspec.is_file():
        raise SystemExit(f"error: missing Flutter pubspec: {pubspec}")
    for line in pubspec.read_text(encoding="utf-8").splitlines():
        match = re.fullmatch(r"name\s*:\s*([^#]+?)(?:\s+#.*)?", line)
        if not match:
            continue
        name = match.group(1).strip().strip("'\"")
        if not PACKAGE_NAME_RE.fullmatch(name):
            raise SystemExit(f"error: invalid Flutter package name in {pubspec}: {name!r}")
        return name
    raise SystemExit(f"error: missing top-level package name in {pubspec}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--widget-path", required=True)
    parser.add_argument("--class-name", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    project = Path(args.project_root).resolve()
    widget = project_path(project, args.widget_path)
    out = project_path(project, args.out)
    try:
        widget_import = widget.relative_to(project / "lib")
    except ValueError as exc:
        raise SystemExit(f"error: shared widget must be under {project / 'lib'}: {widget}") from exc
    if widget.suffix != ".dart":
        raise SystemExit(f"error: shared widget must be a Dart file: {widget}")
    if not CLASS_NAME_RE.fullmatch(args.class_name):
        raise SystemExit(f"error: invalid Dart class name: {args.class_name!r}")

    package = read_package_name(project / "pubspec.yaml")
    import_path = widget_import.as_posix()
    dart = f"""// GENERATED by iFF generate_shared_component_test.py — DO NOT EDIT BY HAND.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:{package}/{import_path}';

void main() {{
  testWidgets('{args.class_name} renders', (WidgetTester tester) async {{
    await tester.pumpWidget(const MaterialApp(home: {args.class_name}()));
    expect(find.byType({args.class_name}), findsOneWidget);
  }});
}}
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dart, encoding="utf-8")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
