#!/usr/bin/env python3
"""Generate ONE same-source design fixture for any feature (invariants ②⑦).

The fixture's content is the DESIGN's displayed values — sourced from generate_canvas's per-state
`<canvas>.dart.slots.json` seeds ({nodeId -> design text}) — so the widget test, preview, runtime
page, and screenshot all read the SAME values and therefore match the design. The runtime
repository fills the same {nodeId -> value} shape from the real DTO (Layer 2 / invariant ④); mock
and API are interchangeable and switching to equal values changes nothing visible.

Feature-agnostic: pass --feature and one slots.json per visible state.

  make_visual_fixture.py --feature withdraw \
      --slots main=lib/.../withdraw_main_canvas.dart.slots.json \
      --slots fixed=lib/.../withdraw_fixed_canvas.dart.slots.json \
      --out lib/features/withdraw/data/withdraw_visual_fixture.dart
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_") if part)


def dart_str(value) -> str:
    return json.dumps("" if value is None else str(value), ensure_ascii=False)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--feature", required=True, help="feature name, e.g. withdraw / my_loan")
    p.add_argument("--slots", action="append", default=[], metavar="STATE=slots.json",
                   help="one per visible state; repeatable")
    p.add_argument("--out", required=True)
    a = p.parse_args()

    if not a.slots:
        raise SystemExit("ERROR: at least one --slots STATE=path is required "
                         "(use generate_canvas's <canvas>.dart.slots.json design seeds)")

    states: dict[str, dict] = {}
    for spec in a.slots:
        if "=" not in spec:
            raise SystemExit(f"ERROR: --slots must be STATE=path, got: {spec}")
        state, path = spec.split("=", 1)
        seed = json.loads(Path(path).read_text(encoding="utf-8"))
        if not isinstance(seed, dict):
            raise SystemExit(f"ERROR: slots seed is not a node->value map: {path}")
        states[state.strip()] = seed

    cls = pascal(a.feature) + "VisualFixture"
    lines = [
        "// GENERATED by iFF make_visual_fixture.py — DO NOT EDIT BY HAND.",
        "// 同源设计 fixture(不变量②⑦):内容=设计稿展示值(来自 generate_canvas 的 slots.json 种子)。",
        "// test / preview / 运行时页面 / 截图同读这一份;运行时 repository 按同样的 {nodeId->值}",
        "// 形状用真实 DTO 覆盖(不变量④),切同值零视觉变化。",
        "",
        f"abstract final class {cls} {{",
        "  /// 各可见状态的动态文本槽种子(节点id -> 设计展示值)。",
        "  static const Map<String, Map<String, String>> states = <String, Map<String, String>>{",
    ]
    for state, seed in states.items():
        entries = ", ".join(f"{dart_str(k)}: {dart_str(v)}" for k, v in seed.items())
        lines.append(f"    {dart_str(state)}: <String, String>{{{entries}}},")
    lines.append("  };")
    lines.append("")
    state_list = ", ".join(dart_str(s) for s in states)
    lines.append(f"  static const List<String> stateNames = <String>[{state_list}];")
    lines.append("")
    lines.append("  /// 取某状态的同源槽位(缺省空 map);页面用 `Canvas(slotText: of(state))` 注入。")
    lines.append(f"  static Map<String, String> of(String state) => states[state] ?? const <String, String>{{}};")
    lines.append("}")

    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"out": str(out), "class": cls, "states": list(states),
                      "slotCounts": {s: len(v) for s, v in states.items()}}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
