#!/usr/bin/env python3
"""Prepare and verify feature packaging between assembly RED and GREEN."""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import shutil
import time


ASSET_LITERAL_RE = re.compile(r"['\"](assets/[^'\"]+)['\"]")
FONT_FAMILY_RE = re.compile(r"fontFamily:\s*['\"]([^'\"]+)['\"]")
FONT_TARGETS = {"SF Pro Text": "fonts/SFProText.ttf"}
DEFAULT_FONT_SOURCES = {"SF Pro Text": Path("/System/Library/Fonts/SFNS.ttf")}


class PackagingError(RuntimeError):
    pass


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_sha256(value: dict) -> str:
    payload = json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def normalize_project_path(value: str) -> str:
    path = PurePosixPath(value)
    if path.is_absolute() or ".." in path.parts or not path.parts or path.parts[0] != "assets":
        raise PackagingError(f"invalid project asset path: {value}")
    return path.as_posix()


def collect_requirements(spec_root: Path, project_root: Path) -> dict:
    feature_key = spec_root.name
    presentation = project_root / "lib" / feature_key / "presentation"
    canvases = sorted(presentation.glob("*_canvas.dart"))
    if not canvases:
        raise PackagingError(f"no generated board canvases found: {presentation}")

    asset_files: set[str] = set()
    fonts: set[str] = set()
    for canvas in canvases:
        text = canvas.read_text(encoding="utf-8")
        if not text.startswith("// GENERATED by iFF generate_canvas.py"):
            raise PackagingError(f"canvas is not an iFF generated artifact: {canvas}")
        asset_files.update(normalize_project_path(value) for value in ASSET_LITERAL_RE.findall(text))
        fonts.update(value.strip() for value in FONT_FAMILY_RE.findall(text) if value.strip())

    missing_assets = [value for value in sorted(asset_files) if not (project_root / value).is_file()]
    if missing_assets:
        raise PackagingError(f"referenced board assets are missing: {missing_assets}")
    unsupported_fonts = sorted(fonts - FONT_TARGETS.keys())
    if unsupported_fonts:
        raise PackagingError(f"required font families have no deterministic package mapping: {unsupported_fonts}")

    return {
        "canvases": [path.relative_to(project_root).as_posix() for path in canvases],
        "assetFiles": sorted(asset_files),
        "assetDirectories": sorted(
            {PurePosixPath(value).parent.as_posix().rstrip("/") + "/" for value in asset_files}
        ),
        "fonts": [
            {"asset": FONT_TARGETS[family], "family": family}
            for family in sorted(fonts)
        ],
    }


def _validate_manifest(
    root: Path, manifest: object, label: str, *, verify_files: bool = True
) -> dict[str, str]:
    if not isinstance(manifest, dict) or not manifest:
        raise PackagingError(f"adoption {label} manifest missing")
    validated: dict[str, str] = {}
    for relative, expected_sha256 in manifest.items():
        if not isinstance(relative, str) or not isinstance(expected_sha256, str):
            raise PackagingError(f"adoption {label} manifest invalid")
        candidate = (root / relative).resolve()
        try:
            candidate.relative_to(root)
        except ValueError as exc:
            raise PackagingError(f"adoption {label} path escapes its root: {relative}") from exc
        if verify_files and (
            not candidate.is_file() or sha256(candidate) != expected_sha256
        ):
            raise PackagingError(f"adopted {label} changed: {relative}")
        validated[relative] = expected_sha256
    return validated


def pre_green_evidence_snapshot(spec_root: Path, *, require_pre_green: bool) -> dict:
    evidence_path = spec_root / "interaction_test_evidence.json"
    if not evidence_path.is_file():
        raise PackagingError(f"pre-GREEN evidence missing before packaging: {evidence_path}")
    try:
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise PackagingError(f"pre-GREEN evidence is invalid JSON: {exc}") from exc
    guard = evidence.get("guard") or {}
    mode = guard.get("mode", "strict_tdd")
    if mode not in {"strict_tdd", "preexisting_green_adoption"}:
        raise PackagingError("pre-GREEN evidence mode is invalid")
    initial_phase = "red_verified" if mode == "strict_tdd" else "adoption_verified"
    allowed_phases = {initial_phase} if require_pre_green else {
        initial_phase, "green_verified", "green_failed"
    }
    if evidence.get("schemaVersion") != 1 or guard.get("runner") != "assembly_tdd_guard.py":
        raise PackagingError("pre-GREEN evidence was not issued by assembly_tdd_guard.py")
    if guard.get("phase") not in allowed_phases:
        raise PackagingError("guarded pre-GREEN evidence phase is invalid for packaging")
    if guard.get("specRoot") != str(spec_root.resolve()):
        raise PackagingError("guarded pre-GREEN evidence spec root mismatch")
    run_id = guard.get("runId")
    if not isinstance(run_id, str) or not run_id:
        raise PackagingError("guarded pre-GREEN evidence run id missing")
    record_name = "red" if mode == "strict_tdd" else "adoption"
    record = evidence.get(record_name) or {}
    exit_code = record.get("exit_code", record.get("exitCode"))
    failure_kind = record.get("failure_kind", record.get("failureKind"))
    if mode == "strict_tdd":
        if exit_code in (0, None):
            raise PackagingError("RED evidence must have a nonzero exit code before packaging")
        if failure_kind != "missing_feature_behavior":
            raise PackagingError(
                "RED evidence failure_kind must be missing_feature_behavior before packaging"
            )
    elif exit_code != 0 or record.get("authorization") != "preexisting-green":
        raise PackagingError("preexisting GREEN adoption is not explicitly authorized and passing")
    if require_pre_green and evidence.get("green") not in (None, {}):
        raise PackagingError("GREEN evidence already exists; packaging cannot be backfilled")
    if record.get("runner") != "assembly_tdd_guard.py" or record.get("run_id") != run_id:
        raise PackagingError("pre-GREEN record provenance does not match the guarded run")
    started_at_ns = record.get("started_at_ns", record.get("startedAtNs"))
    completed_at_ns = record.get("completed_at_ns", record.get("completedAtNs"))
    if (
        not isinstance(started_at_ns, int)
        or not isinstance(completed_at_ns, int)
        or completed_at_ns < started_at_ns
    ):
        raise PackagingError("guarded pre-GREEN invocation chronology invalid")
    command = record.get("command")
    if not isinstance(command, str) or not command:
        raise PackagingError("guarded pre-GREEN command missing")
    project_root = guard.get("projectRoot")
    test_target = guard.get("testTarget")
    if not isinstance(project_root, str) or not isinstance(test_target, str):
        raise PackagingError("guarded pre-GREEN project/test provenance missing")
    manifests: dict[str, dict[str, str]] = {}
    if mode == "preexisting_green_adoption":
        project_path = Path(project_root).resolve()
        verify_files = guard.get("phase") == initial_phase
        manifests = {
            "sourceFiles": _validate_manifest(
                project_path, record.get("source_files"), "source", verify_files=verify_files
            ),
            "testFiles": _validate_manifest(
                project_path, record.get("test_files"), "test", verify_files=verify_files
            ),
            "contractFiles": _validate_manifest(
                spec_root.resolve(), record.get("contract_files"), "contract", verify_files=verify_files
            ),
        }
    snapshot = {
        "mode": mode,
        "exitCode": exit_code,
        "command": command,
        "runId": run_id,
        "runner": record["runner"],
        "startedAtNs": started_at_ns,
        "completedAtNs": completed_at_ns,
        "recordSha256": canonical_sha256(record),
        "projectRoot": project_root,
        "specRoot": str(spec_root.resolve()),
        "testTarget": test_target,
    }
    if mode == "strict_tdd":
        snapshot["failureKind"] = failure_kind
    else:
        snapshot["authorization"] = record["authorization"]
        snapshot.update(manifests)
    return snapshot


def red_evidence_snapshot(spec_root: Path, *, require_pre_green: bool) -> dict:
    snapshot = pre_green_evidence_snapshot(spec_root, require_pre_green=require_pre_green)
    if snapshot.get("mode") != "strict_tdd":
        raise PackagingError("expected strict guarded RED evidence")
    return snapshot


def indentation(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def section_end(lines: list[str], start: int, maximum_indent: int) -> int:
    for index in range(start + 1, len(lines)):
        if lines[index].strip() and indentation(lines[index]) <= maximum_indent:
            return index
    return len(lines)


def ensure_flutter(lines: list[str]) -> int:
    for index, line in enumerate(lines):
        if line == "flutter:":
            return index
    if lines and lines[-1]:
        lines.append("")
    lines.append("flutter:")
    return len(lines) - 1


def ensure_asset_registrations(lines: list[str], directories: list[str]) -> None:
    if not directories:
        return
    flutter_index = ensure_flutter(lines)
    flutter_end = section_end(lines, flutter_index, 0)
    assets_index = next(
        (index for index in range(flutter_index + 1, flutter_end) if lines[index] == "  assets:"),
        None,
    )
    if assets_index is None:
        assets_index = flutter_end
        lines[assets_index:assets_index] = ["  assets:"]
    assets_end = section_end(lines, assets_index, 2)
    existing = {
        line.strip()[2:].strip()
        for line in lines[assets_index + 1:assets_end]
        if line.strip().startswith("- ")
    }
    additions = [f"    - {value}" for value in directories if value not in existing]
    lines[assets_end:assets_end] = additions


def ensure_font_registration(lines: list[str], family: str, asset: str) -> None:
    flutter_index = ensure_flutter(lines)
    flutter_end = section_end(lines, flutter_index, 0)
    fonts_index = next(
        (index for index in range(flutter_index + 1, flutter_end) if lines[index] == "  fonts:"),
        None,
    )
    if fonts_index is None:
        lines[flutter_end:flutter_end] = [
            "  fonts:",
            f"    - family: {family}",
            "      fonts:",
            f"        - asset: {asset}",
        ]
        return

    fonts_end = section_end(lines, fonts_index, 2)
    family_index = next(
        (
            index
            for index in range(fonts_index + 1, fonts_end)
            if lines[index] == f"    - family: {family}"
        ),
        None,
    )
    if family_index is None:
        lines[fonts_end:fonts_end] = [
            f"    - family: {family}",
            "      fonts:",
            f"        - asset: {asset}",
        ]
        return

    family_end = fonts_end
    for index in range(family_index + 1, fonts_end):
        if lines[index].startswith("    - family: "):
            family_end = index
            break
    expected = f"        - asset: {asset}"
    if expected in lines[family_index + 1:family_end]:
        return
    nested_fonts = next(
        (
            index
            for index in range(family_index + 1, family_end)
            if lines[index] == "      fonts:"
        ),
        None,
    )
    if nested_fonts is None:
        lines[family_index + 1:family_index + 1] = ["      fonts:", expected]
    else:
        lines[nested_fonts + 1:nested_fonts + 1] = [expected]


def write_pubspec(pubspec: Path, requirements: dict) -> None:
    lines = pubspec.read_text(encoding="utf-8").splitlines()
    ensure_asset_registrations(lines, requirements["assetDirectories"])
    for font in requirements["fonts"]:
        ensure_font_registration(lines, font["family"], font["asset"])
    temporary = pubspec.with_suffix(pubspec.suffix + ".iff-packaging.tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temporary.replace(pubspec)


def prepare(args: argparse.Namespace) -> int:
    spec_root = Path(args.spec_root).expanduser().resolve()
    project_root = Path(args.project_root).expanduser().resolve()
    pubspec = Path(args.pubspec).expanduser().resolve()
    out = Path(args.out).expanduser().resolve()
    if not spec_root.is_dir():
        raise PackagingError(f"spec root not found: {spec_root}")
    if not pubspec.is_file() or pubspec.parent != project_root:
        raise PackagingError(f"pubspec must be the project-root pubspec: {pubspec}")

    requirements = collect_requirements(spec_root, project_root)
    pre_green_evidence = pre_green_evidence_snapshot(spec_root, require_pre_green=True)
    font_source_override = Path(args.font_source).expanduser().resolve() if args.font_source else None
    for font in requirements["fonts"]:
        target = project_root / font["asset"]
        if target.is_file():
            continue
        source = font_source_override or DEFAULT_FONT_SOURCES[font["family"]]
        if not source.is_file():
            raise PackagingError(
                f"required font source missing for {font['family']}: {source}"
            )

    lock_path = project_root / ".iff" / "assembly_packaging.lock"
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a+", encoding="utf-8") as lock_handle:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX)
        for font in requirements["fonts"]:
            target = project_root / font["asset"]
            if not target.is_file():
                target.parent.mkdir(parents=True, exist_ok=True)
                source = font_source_override or DEFAULT_FONT_SOURCES[font["family"]]
                shutil.copyfile(source, target)
        write_pubspec(pubspec, requirements)

    file_hashes = {
        value: sha256(project_root / value)
        for value in requirements["assetFiles"]
    }
    file_hashes.update(
        {font["asset"]: sha256(project_root / font["asset"]) for font in requirements["fonts"]}
    )
    prepared_at_ns = time.time_ns()
    if prepared_at_ns <= pre_green_evidence["completedAtNs"]:
        raise PackagingError("packaging evidence must be newer than guarded pre-GREEN evidence")
    evidence = {
        "schemaVersion": 2,
        "phase": (
            "post_red_pre_green"
            if pre_green_evidence["mode"] == "strict_tdd"
            else "post_adoption_pre_green"
        ),
        "preparedBy": "prepare_assembly_packaging.py",
        "preparedAtNs": prepared_at_ns,
        "tddRunId": pre_green_evidence["runId"],
        "testProvenanceMode": pre_green_evidence["mode"],
        "specRoot": str(spec_root),
        "projectRoot": str(project_root),
        "pubspec": str(pubspec),
        "pubspecSha256AtPrepare": sha256(pubspec),
        "preGreenEvidence": pre_green_evidence,
        **requirements,
        "fileSha256": dict(sorted(file_hashes.items())),
    }
    if pre_green_evidence["mode"] == "strict_tdd":
        evidence["redEvidence"] = pre_green_evidence
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_suffix(out.suffix + ".tmp")
    temporary.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(out)
    failures = validate_evidence(out)
    if failures:
        out.unlink(missing_ok=True)
        raise PackagingError("; ".join(failures))
    print(
        "PASS: assembly packaging prepared "
        f"assets={len(requirements['assetDirectories'])} fonts={len(requirements['fonts'])}"
    )
    return 0


def validate_evidence(evidence_path: Path) -> list[str]:
    if not evidence_path.is_file():
        return [f"assembly_packaging.json missing: {evidence_path}"]
    try:
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"assembly packaging evidence unreadable: {exc}"]
    failures: list[str] = []
    valid_phases = {"post_red_pre_green", "post_adoption_pre_green"}
    if evidence.get("schemaVersion") != 2 or evidence.get("phase") not in valid_phases:
        failures.append("assembly packaging evidence schema/phase invalid")
        return failures
    spec_root = Path(evidence.get("specRoot", ""))
    project_root = Path(evidence.get("projectRoot", ""))
    pubspec = Path(evidence.get("pubspec", ""))
    if not spec_root.is_dir() or not project_root.is_dir() or not pubspec.is_file():
        failures.append("assembly packaging evidence paths are no longer valid")
        return failures
    if spec_root.resolve() != evidence_path.parent.resolve():
        failures.append("assembly packaging evidence belongs to a different spec root")
    if pubspec.resolve() != (project_root / "pubspec.yaml").resolve():
        failures.append("assembly packaging evidence does not name the project-root pubspec")
    try:
        spec_root.resolve().relative_to(project_root.resolve())
    except ValueError:
        failures.append("assembly packaging spec root is outside the recorded project root")
    if failures:
        return failures
    try:
        current = collect_requirements(spec_root, project_root)
        current_pre_green_evidence = pre_green_evidence_snapshot(
            spec_root, require_pre_green=False
        )
    except PackagingError as exc:
        failures.append(str(exc))
        return failures
    recorded_pre_green = evidence.get("preGreenEvidence", evidence.get("redEvidence"))
    if recorded_pre_green != current_pre_green_evidence:
        failures.append("pre-GREEN evidence changed after assembly packaging")
    prepared_at_ns = evidence.get("preparedAtNs")
    if (
        evidence.get("preparedBy") != "prepare_assembly_packaging.py"
        or evidence.get("tddRunId") != current_pre_green_evidence.get("runId")
        or evidence.get("testProvenanceMode") != current_pre_green_evidence.get("mode")
    ):
        failures.append("assembly packaging provenance does not match guarded pre-GREEN evidence")
    if (
        not isinstance(prepared_at_ns, int)
        or prepared_at_ns <= current_pre_green_evidence.get("completedAtNs", prepared_at_ns)
    ):
        failures.append("assembly packaging is not newer than guarded RED")
    for key in ("canvases", "assetFiles", "assetDirectories", "fonts"):
        if evidence.get(key) != current[key]:
            failures.append(f"assembly packaging requirements changed: {key}")
    pubspec_text = pubspec.read_text(encoding="utf-8")
    for directory in current["assetDirectories"]:
        if f"    - {directory}" not in pubspec_text:
            failures.append(f"asset directory not registered in pubspec: {directory}")
    for font in current["fonts"]:
        if f"    - family: {font['family']}" not in pubspec_text:
            failures.append(f"font family not registered in pubspec: {font['family']}")
        if f"        - asset: {font['asset']}" not in pubspec_text:
            failures.append(f"font asset not registered in pubspec: {font['asset']}")
    expected_hashes = evidence.get("fileSha256") or {}
    for value in current["assetFiles"] + [font["asset"] for font in current["fonts"]]:
        path = project_root / value
        if not path.is_file():
            failures.append(f"packaged file missing: {value}")
        elif expected_hashes.get(value) != sha256(path):
            failures.append(f"packaged file hash changed: {value}")
    return failures


def verify(args: argparse.Namespace) -> int:
    failures = validate_evidence(Path(args.evidence).expanduser().resolve())
    if failures:
        raise PackagingError("; ".join(failures))
    print("PASS: assembly packaging evidence is current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    prepare_parser = subparsers.add_parser("prepare")
    prepare_parser.add_argument("--spec-root", required=True)
    prepare_parser.add_argument("--project-root", required=True)
    prepare_parser.add_argument("--pubspec", required=True)
    prepare_parser.add_argument("--font-source")
    prepare_parser.add_argument("--out", required=True)
    verify_parser = subparsers.add_parser("verify")
    verify_parser.add_argument("--evidence", required=True)
    args = parser.parse_args()
    try:
        return prepare(args) if args.command == "prepare" else verify(args)
    except PackagingError as exc:
        print(f"ERROR: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
