#!/usr/bin/env python3
"""Exercise main-side rejection and accepted assembly completion evidence."""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")


def make_complete_spec(root: Path, scripts: Path, *, complete_green: bool = True) -> Path:
    project = root / "project"
    feature = project / "lanhu" / "specs" / "complete-feature"
    board = feature / "board-a"
    board.mkdir(parents=True)
    presentation = project / "lib" / "complete-feature" / "presentation"
    presentation.mkdir(parents=True)
    (presentation / "board_a_canvas.dart").write_text(
        "// GENERATED by iFF generate_canvas.py\nconst syntheticCanvas = true;\n",
        encoding="utf-8",
    )
    pubspec = project / "pubspec.yaml"
    pubspec.write_text("name: completion_fixture\nflutter:\n", encoding="utf-8")
    test_target = project / "test" / "complete-feature"
    test_target.mkdir(parents=True)
    (test_target / "feature_test.dart").write_text("void main() {}\n", encoding="utf-8")
    fake_flutter = project / "fake_flutter.py"
    fake_flutter.write_text(
        "#!/usr/bin/env python3\n"
        "from pathlib import Path\n"
        "counter = Path(__file__).with_suffix('.count')\n"
        "count = int(counter.read_text() if counter.exists() else '0') + 1\n"
        "counter.write_text(str(count))\n"
        f"trace = Path({str(board / 'actual_layout_trace.json')!r})\n"
        "if count >= 2:\n"
        "    trace.write_text('{\"pageType\":\"RuntimePage\",\"nodes\":{\"node-1\":{\"present\":true}}}')\n"
        "raise SystemExit(1 if count == 1 else 0)\n",
        encoding="utf-8",
    )
    fake_flutter.chmod(0o755)
    write_json(board / "render_fidelity_report.json", {"ok": True, "assetShapeChecked": True})
    write_json(board / "artifact_digest.json", {})
    write_json(board / "shared_components.local.json", {"components": []})
    write_json(board / "implementation_plan.json", {"prefilledBy": "prefill_implementation_plan.py"})
    write_json(board / "actual_layout_trace.json", {"pageType": "RuntimePage", "nodes": {"node-1": {"present": True}}})
    guarded_red = run(
        scripts / "assembly_tdd_guard.py",
        "red",
        "--spec-root",
        str(feature),
        "--project-root",
        str(project),
        "--test-target",
        "test/complete-feature",
        "--failure-kind",
        "missing_feature_behavior",
        "--flutter",
        str(fake_flutter),
    )
    assert guarded_red.returncode == 0, guarded_red.stdout + guarded_red.stderr
    write_json(feature / "wiring_report.json", {"ok": True, "unwired": []})
    write_json(feature / "api_integration_report.json", {"missing": []})
    write_json(feature / "diff_report.json", {"assetIssues": [], "textIssues": []})
    write_json(feature / "visual_manifest.json", {"actual_source": "simulator_screenshot"})
    (feature / "actual.png").write_bytes(b"fake-simulator-png")
    write_json(feature / "worker_compliance.json", {})
    packaged = subprocess.run(
        [
            sys.executable,
            str(scripts / "prepare_assembly_packaging.py"),
            "prepare",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--pubspec",
            str(pubspec),
            "--out",
            str(feature / "assembly_packaging.json"),
        ],
        text=True,
        capture_output=True,
    )
    assert packaged.returncode == 0, packaged.stdout + packaged.stderr
    if complete_green:
        guarded_green = run(
            scripts / "assembly_tdd_guard.py",
            "green",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/complete-feature",
            "--flutter",
            str(fake_flutter),
        )
        assert guarded_green.returncode == 0, guarded_green.stdout + guarded_green.stderr
    return feature


def run(script: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(script), *args], text=True, capture_output=True
    )


def main() -> int:
    scripts = Path(__file__).resolve().parent
    checker = scripts / "assembly_completion.py"
    with tempfile.TemporaryDirectory(prefix="iff-assembly-completion-") as raw_tmp:
        root = Path(raw_tmp)

        fake_success = root / "fake-success" / "board-a"
        fake_success.mkdir(parents=True)
        worker = subprocess.run([sys.executable, "-c", "pass"])
        assert worker.returncode == 0
        rejected = run(
            checker,
            "verify",
            "--spec-root",
            str(fake_success.parent),
            "--evidence",
            str(fake_success.parent / "assembly_completion.json"),
        )
        assert rejected.returncode != 0, rejected.stdout + rejected.stderr
        assert "completion evidence missing" in (rejected.stdout + rejected.stderr), (
            rejected.stdout + rejected.stderr
        )

        complete = make_complete_spec(root, scripts, complete_green=False)
        fake_flutter = complete.parents[2] / "fake_flutter.py"
        evidence = complete / "assembly_completion.json"
        interaction_evidence = complete / "interaction_test_evidence.json"
        guarded_red_only = json.loads(interaction_evidence.read_text(encoding="utf-8"))
        direct_green = json.loads(json.dumps(guarded_red_only))
        direct_green["guard"]["phase"] = "green_verified"
        direct_green["green"] = {"exit_code": 0}
        write_json(interaction_evidence, direct_green)
        direct_rejected = run(
            checker,
            "issue",
            "--spec-root",
            str(complete),
            "--evidence",
            str(evidence),
        )
        assert direct_rejected.returncode != 0, direct_rejected.stdout + direct_rejected.stderr
        assert "GREEN evidence was not issued by the guarded runner" in (
            direct_rejected.stdout + direct_rejected.stderr
        )
        write_json(interaction_evidence, guarded_red_only)
        guarded_green = run(
            scripts / "assembly_tdd_guard.py",
            "green",
            "--spec-root",
            str(complete),
            "--project-root",
            str(complete.parents[2]),
            "--test-target",
            "test/complete-feature",
            "--flutter",
            str(fake_flutter),
        )
        assert guarded_green.returncode == 0, guarded_green.stdout + guarded_green.stderr

        trace = complete / "board-a" / "actual_layout_trace.json"
        write_json(trace, {"pageType": "RuntimePage", "widgets": {"node-1": {"present": True}}})
        invalid_trace = run(
            checker,
            "issue",
            "--spec-root",
            str(complete),
            "--evidence",
            str(root / "invalid_trace_completion.json"),
        )
        assert invalid_trace.returncode != 0, invalid_trace.stdout + invalid_trace.stderr
        assert "actual layout trace" in invalid_trace.stderr, invalid_trace.stdout + invalid_trace.stderr

        tdd_evidence = json.loads(
            (complete / "interaction_test_evidence.json").read_text(encoding="utf-8")
        )
        green_started_at_ns = tdd_evidence["green"]["started_at_ns"]
        write_json(
            trace,
            {"pageType": "RuntimePage", "nodes": {"node-1": {"present": True}}},
        )
        os.utime(trace, ns=(green_started_at_ns - 1, green_started_at_ns - 1))
        stale_trace = run(
            checker,
            "issue",
            "--spec-root",
            str(complete),
            "--evidence",
            str(root / "stale_trace_completion.json"),
        )
        assert stale_trace.returncode != 0, stale_trace.stdout + stale_trace.stderr
        assert "stale" in stale_trace.stderr, stale_trace.stdout + stale_trace.stderr

        write_json(
            trace,
            {"pageType": "RuntimePage", "nodes": {"node-1": {"present": True, "bbox": [0, 0, 10, 10]}}},
        )
        issued = run(
            checker,
            "issue",
            "--spec-root",
            str(complete),
            "--evidence",
            str(evidence),
        )
        assert issued.returncode == 0, issued.stdout + issued.stderr
        assert evidence.is_file()
        verified = run(
            checker,
            "verify",
            "--spec-root",
            str(complete),
            "--evidence",
            str(evidence),
        )
        assert verified.returncode == 0, verified.stdout + verified.stderr

    print("PASS: exit 0/direct GREEN evidence is rejected; guarded completion is accepted")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
