#!/usr/bin/env python3
"""Regression test for guarded assembly RED -> packaging -> GREEN ordering."""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys
import tempfile


def run(script: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(script), *args],
        text=True,
        capture_output=True,
    )


def main() -> int:
    scripts = Path(__file__).resolve().parent
    guard = scripts / "assembly_tdd_guard.py"
    packaging = scripts / "prepare_assembly_packaging.py"
    with tempfile.TemporaryDirectory(prefix="iff-assembly-tdd-guard-") as raw_tmp:
        project = Path(raw_tmp) / "project"
        feature = project / "lanhu" / "specs" / "home"
        (feature / "board-a").mkdir(parents=True)
        presentation = project / "lib" / "home" / "presentation"
        presentation.mkdir(parents=True)
        (presentation / "home_canvas.dart").write_text(
            "// GENERATED by iFF generate_canvas.py\nconst canvas = true;\n",
            encoding="utf-8",
        )
        test_target = project / "test" / "home"
        test_target.mkdir(parents=True)
        (test_target / "home_test.dart").write_text(
            "// INT-001-HAPPY\nvoid main() {}\n", encoding="utf-8"
        )
        (feature / "interaction_test_plan.json").write_text(
            '{"cases":[{"id":"INT-001-HAPPY"}]}\n', encoding="utf-8"
        )
        pubspec = project / "pubspec.yaml"
        pubspec.write_text("name: guard_fixture\nflutter:\n", encoding="utf-8")

        fake_flutter = project / "fake_flutter.py"
        fake_flutter.write_text(
            "#!/usr/bin/env python3\n"
            "from pathlib import Path\n"
            "import sys\n"
            "counter = Path(__file__).with_suffix('.count')\n"
            "count = int(counter.read_text() if counter.exists() else '0') + 1\n"
            "counter.write_text(str(count))\n"
            f"trace = Path({str(feature / 'board-a' / 'actual_layout_trace.json')!r})\n"
            "if count >= 3:\n"
            "    trace.write_text('{\"pageType\":\"RuntimePage\",\"nodes\":{\"node-1\":{\"present\":true}}}')\n"
            "print(f'fake flutter invocation {count}')\n"
            "raise SystemExit(1 if count == 1 else 0)\n",
            encoding="utf-8",
        )
        fake_flutter.chmod(0o755)
        counter = fake_flutter.with_suffix(".count")
        permission_flutter = project / "permission_flutter.py"
        permission_flutter.write_text(
            "#!/usr/bin/env python3\n"
            "print('/opt/flutter/bin/cache/engine.stamp: Operation not permitted')\n"
            "raise SystemExit(1)\n",
            encoding="utf-8",
        )
        permission_flutter.chmod(0o755)

        (feature / "interaction_test_evidence.json").write_text(
            json.dumps(
                {
                    "red": {
                        "exit_code": 1,
                        "failure_kind": "missing_feature_behavior",
                    },
                    "green": {"exit_code": 0},
                }
            ),
            encoding="utf-8",
        )
        legacy = run(
            packaging,
            "prepare",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--pubspec",
            str(pubspec),
            "--out",
            str(feature / "assembly_packaging.json"),
        )
        assert legacy.returncode != 0, legacy.stdout + legacy.stderr
        assert "assembly_tdd_guard.py" in (legacy.stdout + legacy.stderr), (
            legacy.stdout + legacy.stderr
        )

        permission_red = run(
            guard,
            "red",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/home",
            "--failure-kind",
            "missing_feature_behavior",
            "--flutter",
            str(permission_flutter),
        )
        assert permission_red.returncode != 0, permission_red.stdout + permission_red.stderr
        assert "tooling/environment" in permission_red.stderr

        red = run(
            guard,
            "red",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/home",
            "--failure-kind",
            "missing_feature_behavior",
            "--flutter",
            str(fake_flutter),
        )
        assert red.returncode == 0, red.stdout + red.stderr
        assert counter.read_text(encoding="utf-8") == "1"

        premature_green = run(
            guard,
            "green",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/home",
            "--flutter",
            str(fake_flutter),
        )
        assert premature_green.returncode != 0, premature_green.stdout + premature_green.stderr
        assert "assembly_packaging.json missing" in premature_green.stderr
        assert counter.read_text(encoding="utf-8") == "1"

        packaged = run(
            packaging,
            "prepare",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--pubspec",
            str(pubspec),
            "--out",
            str(feature / "assembly_packaging.json"),
        )
        assert packaged.returncode == 0, packaged.stdout + packaged.stderr

        trace = feature / "board-a" / "actual_layout_trace.json"
        trace.write_text(
            json.dumps({"pageType": "RuntimePage", "nodes": {"node-1": {"present": True}}}),
            encoding="utf-8",
        )
        stale_green = run(
            guard,
            "green",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/home",
            "--flutter",
            str(fake_flutter),
        )
        assert stale_green.returncode != 0, stale_green.stdout + stale_green.stderr
        assert "stale" in stale_green.stderr, stale_green.stdout + stale_green.stderr
        assert counter.read_text(encoding="utf-8") == "2"

        green = run(
            guard,
            "green",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/home",
            "--flutter",
            str(fake_flutter),
        )
        assert green.returncode == 0, green.stdout + green.stderr
        green_evidence = json.loads((feature / "interaction_test_evidence.json").read_text(encoding="utf-8"))
        assert green_evidence["cases"]["INT-001-HAPPY"]["greenRunId"] == green_evidence["green"]["run_id"]
        assert counter.read_text(encoding="utf-8") == "3"
        verified = run(guard, "verify", "--spec-root", str(feature))
        assert verified.returncode == 0, verified.stdout + verified.stderr

        for contract_name in (
            "row.json",
            "interaction_contract.json",
            "interaction_test_plan.json",
            "api_contract.json",
        ):
            value = (
                '{"cases":[{"id":"INT-001-HAPPY"}]}\n'
                if contract_name == "interaction_test_plan.json"
                else "{}\n"
            )
            (feature / contract_name).write_text(value, encoding="utf-8")
        adopted = run(
            guard,
            "adopt",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/home",
            "--flutter",
            str(fake_flutter),
            "--authorization",
            "preexisting-green",
        )
        assert adopted.returncode == 0, adopted.stdout + adopted.stderr
        source = presentation / "home_canvas.dart"
        original_source = source.read_text(encoding="utf-8")
        source.write_text(original_source + "// tampered\n", encoding="utf-8")
        tampered_packaging = run(
            packaging,
            "prepare",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--pubspec",
            str(pubspec),
            "--out",
            str(feature / "assembly_packaging.json"),
        )
        assert tampered_packaging.returncode != 0
        assert "adopted source changed" in (
            tampered_packaging.stdout + tampered_packaging.stderr
        )
        source.write_text(original_source, encoding="utf-8")
        adopted_packaging = run(
            packaging,
            "prepare",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--pubspec",
            str(pubspec),
            "--out",
            str(feature / "assembly_packaging.json"),
        )
        assert adopted_packaging.returncode == 0, adopted_packaging.stdout + adopted_packaging.stderr
        adopted_green = run(
            guard,
            "green",
            "--spec-root",
            str(feature),
            "--project-root",
            str(project),
            "--test-target",
            "test/home",
            "--flutter",
            str(fake_flutter),
        )
        assert adopted_green.returncode == 0, adopted_green.stdout + adopted_green.stderr
        source.write_text(original_source + "// audited post-GREEN repair\n", encoding="utf-8")
        adopted_verified = run(guard, "verify", "--spec-root", str(feature))
        assert adopted_verified.returncode == 0, adopted_verified.stdout + adopted_verified.stderr

    print("PASS: guarded RED and explicitly authorized preexisting GREEN adoption both pass chronology")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
