#!/usr/bin/env python3
"""Public-CLI regression for deterministic board implementation-map handoff."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path


def fail(message: str) -> int:
    print(f"FAIL {message}", file=sys.stderr)
    return 1


def main() -> int:
    scripts = Path(__file__).resolve().parent
    skill = scripts.parent

    with tempfile.TemporaryDirectory(prefix="iff-board-implementation-map-") as tmp_raw:
        tmp = Path(tmp_raw)
        project = (tmp / "project").resolve()
        spec = project / "lanhu" / "specs" / "home" / "首页-等待中"
        spec.mkdir(parents=True)
        row = tmp / "row.json"
        prompt = tmp / "board_prompt.txt"
        row.write_text(json.dumps({"title": "首页-等待中"}, ensure_ascii=False), encoding="utf-8")

        result = subprocess.run(
            [
                sys.executable,
                str(scripts / "make_worker_prompt.py"),
                "--skill-dir",
                str(skill),
                "--mode",
                "board",
                "--row-json",
                str(row),
                "--spec-dir",
                str(spec),
                "--project-root",
                str(project),
                "--out",
                str(prompt),
            ],
            text=True,
            capture_output=True,
        )
        if result.returncode != 0:
            return fail(f"make_worker_prompt exited {result.returncode}: {result.stderr.strip()}")

        generated = prompt.read_text(encoding="utf-8")
        make_command = (
            f"python3 {scripts / 'make_implementation_map.py'} "
            f"--render-plan {spec / 'render_plan.json'} --canvas <OUT> "
            f"--out {spec / 'implementation_map.json'}"
        )
        check_command = (
            f"python3 {scripts / 'check_implementation_map.py'} "
            f"--render-plan {spec / 'render_plan.json'} "
            f"--implementation-map {spec / 'implementation_map.json'}"
        )
        required = (
            make_command,
            check_command,
            "Do NOT inspect `<OUT>.expected.json` with jq or ad-hoc schema fallbacks",
            "`.nodes[0]`, `.expected[0]`, or `.[0]`",
            "The expected artifact is not an implementation-map input",
            "If make_implementation_map.py rejects an unsupported schema, STOP and report its error",
        )
        missing = [item for item in required if item not in generated]
        if missing:
            return fail(f"board prompt lacks deterministic implementation-map handoff: {missing}")

        make_position = generated.index(make_command)
        check_position = generated.index(check_command)
        if make_position >= check_position:
            return fail("implementation-map checker appears before deterministic producer")

        canvas = tmp / "waiting_canvas.dart"
        canvas.write_text("// GENERATED by iFF generate_canvas.py\n", encoding="utf-8")
        invalid_plan = tmp / "invalid_render_plan.json"
        invalid_plan.write_text("[]\n", encoding="utf-8")
        invalid_out = tmp / "invalid_implementation_map.json"
        invalid = subprocess.run(
            [
                sys.executable,
                str(scripts / "make_implementation_map.py"),
                "--render-plan",
                str(invalid_plan),
                "--canvas",
                str(canvas),
                "--out",
                str(invalid_out),
            ],
            text=True,
            capture_output=True,
        )
        if invalid.returncode == 0 or "ERROR render plan must be an object" not in invalid.stderr:
            return fail(
                "unsupported render-plan schema did not fail visibly: "
                f"exit={invalid.returncode} stderr={invalid.stderr.strip()}"
            )

        valid_plan = tmp / "render_plan.json"
        valid_plan.write_text(
            json.dumps(
                {
                    "nodes": {
                        "text-1": {
                            "required": True,
                            "implementation": "text",
                            "bbox": [10, 20, 100, 30],
                        },
                        "shape-1": {
                            "required": True,
                            "implementation": "shape",
                            "bbox": [0, 0, 200, 80],
                        },
                    }
                }
            ),
            encoding="utf-8",
        )
        implementation_map = tmp / "implementation_map.json"
        made = subprocess.run(
            [
                sys.executable,
                str(scripts / "make_implementation_map.py"),
                "--render-plan",
                str(valid_plan),
                "--canvas",
                str(canvas),
                "--out",
                str(implementation_map),
            ],
            text=True,
            capture_output=True,
        )
        if made.returncode != 0:
            return fail(f"deterministic producer failed: {made.stderr.strip()}")

        checked = subprocess.run(
            [
                sys.executable,
                str(scripts / "check_implementation_map.py"),
                "--render-plan",
                str(valid_plan),
                "--implementation-map",
                str(implementation_map),
            ],
            text=True,
            capture_output=True,
        )
        if checked.returncode != 0:
            return fail(f"generated implementation map failed strict checker: {checked.stderr.strip()}")

    print("PASS board prompt uses a schema-safe implementation-map producer")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
