from __future__ import annotations

import json
import hashlib
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "check_data_device_evidence.py"


class CheckDataDeviceEvidenceTest(unittest.TestCase):
    def test_hand_written_observation_evidence_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp)
            test_root = project / "integration_test"
            test_root.mkdir()
            bindings = project / "data_slot_bindings.json"
            runtime = project / "data_runtime_manifest.json"
            evidence = project / "data_device_evidence.json"
            bindings.write_text(json.dumps({"bindings": []}), encoding="utf-8")
            runtime.write_text(json.dumps({"operations": []}), encoding="utf-8")
            evidence.write_text(
                json.dumps(
                    {
                        "platform": "android",
                        "deviceId": "emulator-5554",
                        "cases": {},
                        "observed": ["looks correct"],
                    }
                ),
                encoding="utf-8",
            )

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--bindings",
                    str(bindings),
                    "--runtime-manifest",
                    str(runtime),
                    "--test-root",
                    str(test_root),
                    "--project-root",
                    str(project),
                    "--evidence",
                    str(evidence),
                ],
                capture_output=True,
                text=True,
                check=False,
            )

            self.assertNotEqual(0, result.returncode)
            self.assertIn(
                "must be generated by run_data_device_tests.py",
                result.stdout + result.stderr,
            )

    def test_browser_platform_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp)
            test_root = project / "integration_test"
            test_root.mkdir()
            bindings = project / "data_slot_bindings.json"
            runtime = project / "data_runtime_manifest.json"
            evidence = project / "data_device_evidence.json"
            bindings.write_text(json.dumps({"bindings": []}), encoding="utf-8")
            runtime.write_text(json.dumps({"operations": []}), encoding="utf-8")
            evidence.write_text(
                json.dumps(
                    {
                        "generator": "run_data_device_tests.py",
                        "platform": "browser",
                        "deviceId": "chrome",
                        "command": ["flutter", "test", "--machine", "-d", "chrome"],
                    }
                ),
                encoding="utf-8",
            )

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--bindings",
                    str(bindings),
                    "--runtime-manifest",
                    str(runtime),
                    "--test-root",
                    str(test_root),
                    "--project-root",
                    str(project),
                    "--evidence",
                    str(evidence),
                ],
                capture_output=True,
                text=True,
                check=False,
            )

            self.assertNotEqual(0, result.returncode)
            self.assertIn("target client platform must be android or ios", result.stdout + result.stderr)

    def test_all_current_input_fingerprints_are_required(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp)
            test_root = project / "integration_test"
            lib = project / "lib"
            test_root.mkdir()
            lib.mkdir()
            main = lib / "main.dart"
            test_file = test_root / "data_test.dart"
            pubspec = project / "pubspec.yaml"
            main.write_text("void main() {}\n", encoding="utf-8")
            test_file.write_text("void main() {}\n", encoding="utf-8")
            pubspec.write_text("name: demo\n", encoding="utf-8")
            bindings = project / "data_slot_bindings.json"
            runtime = project / "data_runtime_manifest.json"
            evidence = project / "data_device_evidence.json"
            bindings.write_text(json.dumps({"bindings": []}), encoding="utf-8")
            runtime.write_text(json.dumps({"operations": []}), encoding="utf-8")
            evidence.write_text(
                json.dumps(
                    {
                        "generator": "run_data_device_tests.py",
                        "platform": "android",
                        "deviceId": "emulator-5554",
                        "appHashes": {
                            "lib/main.dart": hashlib.sha256(main.read_bytes()).hexdigest()
                        },
                    }
                ),
                encoding="utf-8",
            )

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--bindings",
                    str(bindings),
                    "--runtime-manifest",
                    str(runtime),
                    "--test-root",
                    str(test_root),
                    "--project-root",
                    str(project),
                    "--evidence",
                    str(evidence),
                ],
                capture_output=True,
                text=True,
                check=False,
            )

            output = result.stdout + result.stderr
            self.assertNotEqual(0, result.returncode)
            self.assertIn("stale device bindingsHash", output)
            self.assertIn("stale device runtimeManifestHash", output)
            self.assertIn("stale device testHashes", output)
            self.assertIn("stale device runtimeInputHashes", output)


if __name__ == "__main__":
    unittest.main()
