#!/usr/bin/env bash

AGP_VERSION='9.2.1'
GRADLE_VERSION='9.4.1'
JDK_MAJOR='17'
COMPILE_SDK='37'
TARGET_SDK='37'
BUILD_TOOLS_VERSION='36.0.0'
COMPOSE_COMPILER_VERSION='2.3.21'
COMPOSE_BOM_VERSION='2026.06.00'
ACTIVITY_VERSION='1.13.0'
LIFECYCLE_VERSION='2.10.0'
ANDROIDX_TEST_CORE_VERSION='1.7.0'
ANDROIDX_TEST_RUNNER_VERSION='1.7.0'
ANDROIDX_TEST_JUNIT_VERSION='1.3.0'
ESPRESSO_VERSION='3.7.0'
JUNIT_VERSION='4.13.2'

print_toolchain() {
  printf '目标工具链... AGP %s / Gradle %s / JDK %s / compileSdk %s / targetSdk %s / Build Tools %s\n' \
    "$AGP_VERSION" "$GRADLE_VERSION" "$JDK_MAJOR" "$COMPILE_SDK" "$TARGET_SDK" "$BUILD_TOOLS_VERSION"
}
